### ISSUE TITLE
Dynamically check for storage space

### ISSUE THREAD

**Issue by Technochips** [tf2classic/TF2CDownloader#3]

**Comment by chloecormier** [comment]
Looks easy to do. You can get the free disk space (in bytes) at the location of the installer with:
```
shutil.disk_usage(".")[2]
```
So, just need to check at some stage if that's greater than 16106127360, and exit if not.

**Comment by chloecormier** [comment]
Added in https://github.com/tf2classic/TF2CDownloader/commit/5769751946c84b77438026a472cbfb83295bab96
